#
# System constants and configurations
#

# Import optimal feature configurations from correlation analysis
# These are loaded dynamically from the optimal_features.py files generated by correlation analysis
from framework.optimal import (
    HTTP_FLOOD_1S, HTTP_FLOOD_10S, HTTP_FLOOD_60S, HTTP_FLOOD_300S,
    MULTIVECTOR_1S, MULTIVECTOR_10S, MULTIVECTOR_60S, MULTIVECTOR_300S,
    SYNACK_1S, SYNACK_10S, SYNACK_60S, SYNACK_300S
)

# Note: Optimal model parameters are now auto-loaded at runtime
# The system automatically uses optimal parameters from hyperparameter optimization when available
# Priority: config params > optimal params > default params

# Default dataset to use when none is specified
DEFAULT_DATASET = 'itp-downstream-http-flood'

# Default time span for feature aggregation in seconds
DEFAULT_TIME_SPAN = 300

# Default model threshold calculation strategies
# Available strategies for all models:
#   - 'mean_plus_3std': threshold = μ + 3σ
#   - 'mse_plus_8std': threshold = MSE + 8σ
#   - 'mse_plus_80std': threshold = MSE + 80σ
#   - 'percentile_99': threshold = P₉₉(errors)
#   - 'percentile_99_5': threshold = P₉₉.₅(errors)
#   - 'percentile_99_9': threshold = P₉₉.₉(errors)
#   - 'exponential_threshold': threshold = μ + k·e^(-λt)·σ
#   - 'sigmoid_threshold': threshold = μ + σ/(1 + e^(-k(x-x₀)))
MODEL_THRESHOLD_STRATEGIES = {
    'autoencoder': 'exponential_threshold',
    'isolation_forest': 'percentile_99_5',
    'one_class_svm': 'mean_plus_3std',
    'local_outlier_factor': 'mse_plus_8std'
}

# Default model hyperparameters
MODEL_DEFAULT_PARAMS = {
    'autoencoder': {
        'hidden_layers': [24, 18, 12],  # Hidden layer dimensions for encoder (decoder mirrors these). Example: [24, 18, 12] creates encoder: input -> 24 -> 18 -> 12 -> latent
        'latent_dim': 8,  # Dimensionality of the latent space (bottleneck layer). Lower = more compression. Typical range: 2-64. Too low may lose important patterns, too high may not compress enough
        'batch_size': 64,  # Batch size for training (default: 64). Higher = faster but more memory. Typical range: 32-256
        'learning_rate': 0.01  # Learning rate for Adam optimizer (default: 0.01). Lower = slower but more stable. Typical range: 0.001-0.1
    },
    'isolation_forest': {
        'contamination': 0.05, # Expected proportion of outliers: 0.01-0.05 (clean data), 0.1-0.2 (noisy data)
        'n_estimators': 200,   # Number of trees in the forest (default: 100). More trees = more stable but slower
        'random_state': 42     # Seed for reproducibility of results
    },
    'one_class_svm': {
        'nu': 0.1,            # Upper bound on fraction of training errors and lower bound on support vectors (0.0-1.0), common values: 0.01-0.05 (strict), 0.1-0.2 (moderate). Lower = tighter boundary
        'kernel': 'rbf',      # Kernel type: 'linear' (fast, simple), 'rbf' (flexible, default), 'poly' (polynomial), 'sigmoid'
        'gamma': 'scale'      # Kernel coefficient: 'scale' (1/(n_features*X.var())), 'auto' (1/n_features), or float, higher values = more complex decision boundary, risk of overfitting
    },
    'local_outlier_factor': {
        'n_neighbors': 20,     # Number of neighbors to use (default: 20). Higher values = smoother decision boundaries
        'contamination': 0.05, # Expected proportion of outliers: 0.01-0.05 (clean data), 0.1-0.2 (noisy data)
        'novelty': True,       # If True, can be used for novelty detection; if False, for outlier detection only
        'random_state': 42,    # Seed for reproducibility of results
        'algorithm': 'auto',   # Algorithm to compute nearest neighbors: 'auto', 'ball_tree', 'kd_tree', 'brute'
        'leaf_size': 30,       # Leaf size for BallTree/KDTree algorithms. Affects construction/query speed (default: 30)
        'metric': 'minkowski', # Distance metric: 'minkowski', 'euclidean', 'manhattan', 'chebyshev', 'cosine', etc.
        'p': 2,                # Power parameter for Minkowski metric (1=Manhattan, 2=Euclidean, inf=Chebyshev)
        'n_jobs': -1           # Number of parallel jobs to run (-1 means using all processors)
    }
}

# Hyperparameter optimization configuration
OPTIMIZATION_CONFIG = {
    'n_iter': 50,
    'scoring': 'anomaly_score'
}

# Default EMA (Exponential Moving Average) configuration
# EMA smoothing is applied to reduce noise in time-series features
# 
# How it works:
#   1. Features listed in 'features' will have EMA versions created (suffix: _ema)
#   2. EMA features are always generated and added to the feature set
#   3. Use 'include_groups': ['ema_smoothed'] in feature_config to select them
#   4. Override 'alpha' per time window using 'ema_alpha' in window config
#
# Alpha parameter (0 < alpha < 1):
#   - Lower values (0.05-0.1): More smoothing, slower response to changes
#   - Higher values (0.2-0.5): Less smoothing, faster response to changes
DEFAULT_EMA_CONFIG = {
    'alpha': 0.1,  # Smoothing factor (0 < alpha < 1). Lower = more smoothing
    'features': [  # Features that will have EMA versions created
        'packet_rate', 
        'bit_rate', 
        'flow_rate', 
        'duration_mean', 
        'bytes_std', 
        'packets_std', 
        'flows_per_second'
    ]
}

DATASETS = {
    'itp-downstream-http-flood': {
        'path': './datasets/itp-downstream-http-flood/raw/',
        'description': 'ITP downstream HTTP flood attack dataset',
        'patterns': {
            'train': 'nfcapd.20250714*.csv',
            'validation': 'nfcapd.20250715*.csv',
            'test': 'nfcapd.2025071[67]*.csv'
        },
        'windows': {
            '1': {
                'feature_config': HTTP_FLOOD_1S,
                'attack_periods': [
                    ('2025-07-16 20:27:14', '2025-07-16 20:32:14'),
                    ('2025-07-16 22:23:07', '2025-07-16 22:23:07'),
                    ('2025-07-16 22:24:57', '2025-07-16 22:25:03'),
                    ('2025-07-16 22:33:05', '2025-07-16 22:33:07'),
                    ('2025-07-17 00:09:16', '2025-07-17 00:09:19'),
                    ('2025-07-17 00:30:15', '2025-07-17 00:30:17'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'mse_plus_40std',
                    'isolation_forest': 'percentile_99_5',
                    'one_class_svm': 'percentile_99_9',
                    'local_outlier_factor': 'mse_plus_3std'
                }
            },
            '10': {
                'feature_config': HTTP_FLOOD_10S,
                'attack_periods': [
                    ('2025-07-16 20:27:10', '2025-07-16 20:37:00'),
                    ('2025-07-16 22:24:50', '2025-07-16 22:25:10'),
                    ('2025-07-16 22:33:00', '2025-07-16 22:33:00'),
                    ('2025-07-17 00:09:10', '2025-07-17 00:09:10'),
                    ('2025-07-17 00:30:10', '2025-07-17 00:30:10'),
                    ('2025-07-17 00:38:00', '2025-07-17 00:51:40'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'percentile_99_5',
                    'one_class_svm': 'percentile_99'
                }
            },
            '60': {
                'feature_config': HTTP_FLOOD_60S,
                'attack_periods': [
                    ('2025-07-16 20:27:00', '2025-07-16 20:37:00'),
                    ('2025-07-16 22:25:00', '2025-07-16 22:25:00'),
                    ('2025-07-16 22:33:00', '2025-07-16 22:33:00'),
                    ('2025-07-17 00:09:00', '2025-07-17 00:09:00'),
                    ('2025-07-17 00:30:00', '2025-07-17 00:30:00'),
                    ('2025-07-17 00:38:00', '2025-07-17 00:50:00'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'percentile_99_5',
                    'one_class_svm': 'mean_plus_3std',
                    'local_outlier_factor': 'sigmoid_threshold'
                }
            },
            '300': {
                'feature_config': HTTP_FLOOD_300S,
                'attack_periods': [
                    ('2025-07-16 20:25:00', '2025-07-16 20:35:00'),
                    ('2025-07-16 22:30:00', '2025-07-16 22:30:00'),
                    ('2025-07-17 00:30:00', '2025-07-17 00:30:00'),
                    ('2025-07-17 00:40:00', '2025-07-17 00:45:00'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'percentile_99_5',
                    'one_class_svm': 'percentile_99'
                }
            }
        }
    },
    'itp-synack-customer-outage': {
        'path': './datasets/itp-synack-customer-outage/raw/',
        'description': 'ITP SYN+ACK flood attack causing customer outage',
        'patterns': {
            'train': ['nfcapd.20251005*.csv', 'nfcapd.20251006*.csv', 'nfcapd.20251007*.csv'],
            'validation': ['nfcapd.20251009*.csv', 'nfcapd.20251010*.csv'],
            'test': ['nfcapd.20251011*.csv', 'nfcapd.20251012*.csv', 'nfcapd.20251013*.csv']
        },
        'windows': {
            '1': {
                'feature_config': SYNACK_1S,
                'attack_periods': [
                    ('2025-10-13 15:26:30', '2025-10-13 17:16:20'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'sigmoid_threshold',
                    'isolation_forest': 'percentile_99_9',
                    'one_class_svm': 'mse_plus_4_5std',
                    'local_outlier_factor': 'percentile_99'
                }
            },
            '10': {
                'feature_config': SYNACK_10S,
                'attack_periods': [
                    ('2025-10-13 15:26:30', '2025-10-13 17:16:20'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'percentile_99_9',
                    'one_class_svm': 'percentile_99_9',
                    'local_outlier_factor': 'percentile_99'
                }
            },
            '60': {
                'feature_config': SYNACK_60S,
                'attack_periods': [
                    ('2025-10-13 15:28:00', '2025-10-13 17:15:00'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'percentile_99_9',
                    'one_class_svm': 'mse_plus_8std',
                    'local_outlier_factor': 'exponential_threshold'
                }
            },
            '300': {
                'feature_config': SYNACK_300S,
                'attack_periods': [
                    ('2025-10-13 15:35:00', '2025-10-13 17:25:00'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'percentile_99_9',
                    'one_class_svm': 'percentile_99_9'
                }
            }
        }
    },
    'itp-multivector-udp-100gbps-peak': {
        'path': './datasets/itp-multivector-udp-100gbps-peak/raw/',
        'description': 'ITP multi-vector UDP flood attack with 100Gbps peak',
        'patterns': {
            'train': ['nfcapd.20251008*.csv', 'nfcapd.20251009*.csv', 'nfcapd.20251010*.csv'],
            'validation': 'nfcapd.20251011*.csv',
            'test': 'nfcapd.2025101[2-6]*.csv',
            'horizon': ['nfcapd.2025101[7-9]*.csv', 'nfcapd.2025102[0-6]*.csv']
        },
        'windows': {
            '1': {
                'feature_config': MULTIVECTOR_1S,
                'attack_periods': [
                    ('2025-10-15 20:28:40', '2025-10-15 20:42:10'),
                    ('2025-10-15 20:53:40', '2025-10-15 21:06:20'),
                    ('2025-10-15 22:44:20', '2025-10-15 22:54:40'),
                    ('2025-10-16 00:10:40', '2025-10-16 00:19:40'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'mse_plus_5_5std',
                    'one_class_svm': 'mse_plus_4_5std',
                    'local_outlier_factor': 'mse_plus_40std'
                }
            },
            '10': {
                'feature_config': MULTIVECTOR_10S,
                'attack_periods': [
                    ('2025-10-15 20:28:40', '2025-10-15 20:42:10'),
                    ('2025-10-15 20:53:40', '2025-10-15 21:06:20'),
                    ('2025-10-15 22:44:20', '2025-10-15 22:54:40'),
                    ('2025-10-16 00:10:40', '2025-10-16 00:19:40'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'percentile_99_5',
                    'one_class_svm': 'percentile_99_5',
                    'local_outlier_factor': 'percentile_99_9'
                }
            },
            '60': {
                'feature_config': MULTIVECTOR_60S,
                'attack_periods': [
                    ('2025-10-15 20:29:00', '2025-10-15 20:42:00'),
                    ('2025-10-15 20:54:00', '2025-10-15 21:03:00'),
                    ('2025-10-15 22:46:00', '2025-10-15 22:54:00'),
                    ('2025-10-16 00:11:00', '2025-10-16 00:18:00'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'exponential_threshold',
                    'isolation_forest': 'percentile_99_5',
                    'one_class_svm': 'mse_plus_8std',
                    'local_outlier_factor': 'percentile_99_9'
                }
            },
            '300': {
                'feature_config': MULTIVECTOR_300S,
                'attack_periods': [
                    ('2025-10-15 20:25:00', '2025-10-15 20:40:00'),
                    ('2025-10-15 20:50:00', '2025-10-15 21:15:00'),
                    ('2025-10-15 22:45:00', '2025-10-15 22:50:00'),
                    ('2025-10-16 00:10:00', '2025-10-16 00:20:00'),
                ],
                'threshold_strategies': {
                    'autoencoder': 'mse_plus_3std',
                    'isolation_forest': 'percentile_99_9',
                    'one_class_svm': 'mse_plus_8std',
                    'local_outlier_factor': 'percentile_99_9'
                }
            }
        }
    },
}
